title: Antonio Squicciarini
logo: assets/img/my_photo_circle.jpg
#url: "https://antosquicciarini.github.io"
#baseurl: ""
#avatar: "/assets/img/my_photo_circle.jpg"
#description
show_downloads: true
theme: jekyll-theme-minimal
